### ISSUE TITLE
how to use the VT Augment widget in ES6 ?!

### ISSUE THREAD

**Issue by CreativeASAP** [VirusTotal/vt-augment#34]
I have faced an error when using the VT Augment widget in ES6.
This is the code:
// Start of code
import React, { useEffect, useRef } from "react";
import VTAugment from "@virustotal/vt-augment";

const VTButton = () => {
  const containerRef = useRef(null);
  const vtaugmentRef = useRef(null);

  const handleButtonClick = () => {
    if (vtaugmentRef.current) {
      vtaugmentRef.current
        .load(
          "https://www.virustotal.com/ui/widget/html/MTMuMTA3LjEyLjUwfHxpcF9hZGRyZXNzfHx7ImJkMSI6ICIjNGQ2Mzg1IiwgImJnMSI6ICIjMzEzZDVhIiwgImJnMiI6ICIjMjIyYzQyIiwgImZnMSI6ICIjZmZmZmZmIiwgInR5cGUiOiAiZGVmYXVsdCJ9fHxzZXNzaW9ufHxmb3VuZHx8djN8fDE2OTYyNjY1MzV8fGYwZjMxMDQ2MDllZmI3NzU1MzBjMmM4NGEzZTYxZDQxNDcwZWRjMDYxOWEyYzA0ZWU2NzFjZjIxNzgwOWRmZjY"
        )
        .openDrawer();
    }
  };

  useEffect(() => {
    if (containerRef.current) {
      vtaugmentRef.current = new VTAugment(containerRef.current, {
        mode: "drawer",
      });
    }
  }, []);

  return (
    <div>
      <svg
        onClick={handleButtonClick}
        width="50px"
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
        version="1.1"
        id="Layer_1"
        x="0px"
        y="0px"
        viewBox="0 0 100 100"
        enableBackground="new 0 0 100 100"
        xmlSpace="preserve"
      >
        <polygon
          points="80.2,94 98.7,75.1 98.7,6 89.3,22.3 89.3,84.6 23.5,84.6 58.3,50 23.5,15.4 82.3,15.4 98.7,6 98.7,6 1.3,6 45.4,50  1.3,94 "
          fill="#394EFF"
        ></polygon>
      </svg>
      <div ref={containerRef}></div>
    </div>
  );
};

export default VTButton;

// End of code

and this is the error:
Uncaught TypeError: import_vt_augment.default is not a constructor
    at VTButton.jsx:20:30
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:7)
    at commitPassiveMountEffects (react-dom.development.js:24866:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:3)
    at flushPassiveEffects (react-dom.development.js:26984:14)
    at performSyncWorkOnRoot (react-dom.development.js:26076:3)
    at flushSyncCallbacks (react-dom.development.js:12042:22)

**Comment by Derekt2** [comment]
same problem here, unable to import in Vue.js framework via `import VTAugment from "@virustotal/vt-augment";`

My guess is this is unsupported as UMD is only option provided
